name: Minecraft Server 1.16.5 Host

on: [push]

jobs:
  run-minecraft-server:
    runs-on: ubuntu-latest

    steps:
    - name: Set up OpenJDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 16

    - name: Download Minecraft Server 1.16.5
      run: |
        mkdir mc_server
        cd mc_server
        wget -O server.jar https://launcher.mojang.com/v1/objects/fe3f7a40c1779f6a9a4a1f9789a64e7a9f545cd5/server.jar

    - name: Accept EULA
      run: echo "eula=true" > mc_server/eula.txt

    - name: Run Minecraft Server 1.16.5
      run: |
        cd mc_server
        # Run server in background
        nohup java -Xmx1024M -Xms1024M -jar server.jar nogui &

        # Wait a bit for server to start
        sleep 20

        # Get IP address of the runner
        IP=$(hostname -I | awk '{print $1}')
        echo "Minecraft Server is running at IP: $IP and Port: 25565"

        # Show server logs tail
        tail -n 20 nohup.out
