name: Minecraft Server 1.16.5 Host

on: [push]

jobs:
  run-minecraft-server:
    runs-on: ubuntu-latest

    steps:
    - name: Set up OpenJDK 16
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 16

    - name: Download Minecraft 1.16.5 server jar dynamically
      run: |
        mkdir mc_server
        cd mc_server

        # Download versions manifest
        curl -s https://launchermeta.mojang.com/mc/game/version_manifest.json -o versions.json

        # Extract URL for 1.16.5 version manifest
        VERSION_URL=$(jq -r '.versions[] | select(.id=="1.16.5") | .url' versions.json)

        # Download version manifest for 1.16.5
        curl -s "$VERSION_URL" -o 1.16.5.json

        # Extract server download URL
        SERVER_JAR_URL=$(jq -r '.downloads.server.url' 1.16.5.json)

        # Download server jar
        wget -O server.jar "$SERVER_JAR_URL"

    - name: Accept EULA
      run: echo "eula=true" > mc_server/eula.txt

    - name: Run Minecraft Server 1.16.5
      run: |
        cd mc_server
        nohup java -Xmx1024M -Xms1024M -jar server.jar nogui &

        sleep 20

        IP=$(hostname -I | awk '{print $1}')
        echo "Minecraft Server is running at IP: $IP and Port: 25565"

        tail -n 20 nohup.out
