name: PaperMC Minecraft Server 1.16.5 Host

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-papermc-server:
    runs-on: ubuntu-latest

    steps:
      - name: Set up OpenJDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16

      - name: Download PaperMC 1.16.5 server jar
        run: |
          mkdir mc_server
          cd mc_server
          curl -sL https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/788/downloads/paper-1.16.5-788.jar -o paper.jar

      - name: Accept EULA
        run: echo "eula=true" > mc_server/eula.txt

      - name: Run PaperMC Server
        run: |
          cd mc_server
          nohup java -Xmx1024M -Xms1024M -jar paper.jar nogui > nohup.out 2>&1 &
          sleep 20
          echo "PaperMC Server 1.16.5 is running."
          tail -n 20 nohup.out
