name: PaperMC Minecraft Server 1.16.5 Host

on:
  push:
    branches:
      - main

jobs:
  run-papermc-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for HTML files)
        uses: actions/checkout@v3

      - name: Install jq and wget
        run: sudo apt-get update && sudo apt-get install -y jq wget

      - name: Set up OpenJDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 16

      - name: Download PaperMC versions JSON and get server jar URL for 1.16.5
        run: |
          mkdir mc_server
          cd mc_server
          curl -s https://gist.githubusercontent.com/osipxd/6119732e30059241c2192c4a8d2218d9/raw/d8b5faadcfdfadfa0ff58dbf7c04cd10de16c678/paper-versions.json -o paper-versions.json
          PAPER_URL=$(jq -r '.versions["1.16.5"]' paper-versions.json)
          echo "PaperMC 1.16.5 server jar URL: $PAPER_URL"
          wget -O paper.jar "$PAPER_URL"

      - name: Accept EULA
        run: echo "eula=true" > mc_server/eula.txt

      - name: Add basic HTML server options page
        run: |
          cat << 'EOF' > mc_server/server_options.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>PaperMC Server Options</title>
          </head>
          <body>
            <h1>PaperMC Minecraft Server 1.16.5 Options</h1>
            <form>
              <label for="maxplayers">Max Players:</label>
              <input type="number" id="maxplayers" name="maxplayers" min="1" max="100" value="20" /><br/><br/>
              <label for="motd">Message of the Day (MOTD):</label><br/>
              <input type="text" id="motd" name="motd" value="Welcome to PaperMC Server!" size="50"/><br/><br/>
              <input type="submit" value="Apply (Note: Static demo only)" />
            </form>
            <p>This is a static demo page and cannot modify the running server in this workflow.</p>
          </body>
          </html>
          EOF

      - name: Run PaperMC server and serve HTML options page
        run: |
          cd mc_server
          # Run PaperMC server in background
          nohup java -Xmx1024M -Xms1024M -jar paper.jar nogui > paper.log 2>&1 &
          SERVER_PID=$!
          echo "PaperMC server started with PID $SERVER_PID"
          # Serve the static HTML page on port 8080 using Python3 HTTP server
          nohup python3 -m http.server 8080 > http.log 2>&1 &
          HTTP_PID=$!
          echo "HTTP server started with PID $HTTP_PID"
          # Wait 30 seconds to let server start
          sleep 30
          IP=$(hostname -I | awk '{print $1}')
          echo "PaperMC Server 1.16.5 is running at IP: $IP port: 25565"
          echo "HTML server is running at IP: $IP port: 8080"
          echo "Tail last 20 lines of PaperMC server log:"
          tail -n 20 paper.log
          # Kill background processes before job ends
          kill $SERVER_PID $HTTP_PID || true
