name: Run on Self-Hosted Linux Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-on-self-hosted:
    runs-on: self-hosted
    # You can add labels to target specific self-hosted runners like:
    # runs-on: [self-hosted, linux, my-label]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display Linux info
        run: |
          echo "Running on self-hosted runner"
          uname -a
          lsb_release -a || cat /etc/*-release || echo "No release info"

      - name: Run interactive-style script (example)
        run: |
          echo "You can run any Linux commands here."
          echo "Current directory content:"
          ls -la
          # Add your commands here
